# <a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 6</b></center>    
<pre>    

# Name :- Kevin Kagathara
# Enrollment No :- 22010101080

# import necessary libraries

In [38]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

# Import diabetes.csv data ser using sklearn

In [2]:
df = pd.read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Check the distribution of the target

In [4]:
df.Outcome.value_counts()

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64

# Replace zeros with NaN for specific columns

In [5]:
# sum(df['Glucose'] == 0)
# sum(df['Insulin'] == 0)

(df == 0).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [6]:
c = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']

In [7]:
df[c] = df[c].replace(0,np.nan)

# Check for missing values

In [8]:
# (df == 0).sum()
df.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

# Fill missing values with median

In [37]:
# df['Glucose'] = df['Glucose'].fillna((df['Glucose']).median) 
# df['Glucose']

0      148.0
1       85.0
2      183.0
3       89.0
4      137.0
       ...  
763    101.0
764    122.0
765    121.0
766    126.0
767     93.0
Name: Glucose, Length: 768, dtype: object

In [9]:
df[c] = df[c].fillna(df[c].median())
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0    125.0  33.6   
1              1     85.0           66.0           29.0    125.0  26.6   
2              8    183.0           64.0           29.0    125.0  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0           40.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
764            2    122.0           70.0           27.0    125.0  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0           60.0           29.0    125.0  30.1   
767            1     93.0           70.0           31.0    125.0  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Visualize Distributions

In [12]:
import seaborn as sns

In [13]:
%matplotlib qt

In [15]:
sns.pairplot(df,hue='Outcome')

C:\Users\kpkag\anaconda3\Lib\site-packages\seaborn\axisgrid.py:118: UserWarning: The figure layout has changed to tight
  self._figure.tight_layout(*args, **kwargs)


In [19]:
sns.heatmap(df.corr(),annot = True)

<Axes: >

# Convert Target data into interger code

In [10]:
label_encoder = LabelEncoder()

In [11]:
# df['Outcome'] = df['Outcome'].replace({"Diabetic": 1, "Non Diabetic": 0})
# df['Outcome'] = df['Outcome'].map({"Diabetic": 1, "Non Diabetic": 0})
df['Outcome'] = label_encoder.fit_transform(df['Outcome'])


df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0    125.0  33.6   
1              1     85.0           66.0           29.0    125.0  26.6   
2              8    183.0           64.0           29.0    125.0  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0           40.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
764            2    122.0           70.0           27.0    125.0  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0           60.0           29.0    125.0  30.1   
767            1     93.0           70.0           31.0    125.0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        0  
1                       0.351   31        1  
2                       0.672   32        0  
3                       0.167   21        1  
4                       2.288   33        0  
..                        ...  ...      ...  
763                     0.171   63        1  
764                     0.340   27        1  
765                     0.245   30        1  
766                     0.349   47        0  
767                     0.315   23        1  

[768 rows x 9 columns]

# Divide the data into input and output

In [59]:
# X = df.iloc[:20:,:-1:]
X = df.iloc[::,:-1:]
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0    125.0  33.6   
1              1     85.0           66.0           29.0    125.0  26.6   
2              8    183.0           64.0           29.0    125.0  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0           40.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
764            2    122.0           70.0           27.0    125.0  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0           60.0           29.0    125.0  30.1   
767            1     93.0           70.0           31.0    125.0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [60]:
Y = df['Outcome']
# Y = df.iloc[:20:,8::]
Y

0      0
1      1
2      0
3      1
4      0
      ..
763    1
764    1
765    1
766    0
767    1
Name: Outcome, Length: 768, dtype: int32

# Splitting the dataset into the Training set and Test set

In [61]:
x_train,x_test,y_train,y_test = train_test_split(X,Y, train_size=0.7, random_state=0)


In [62]:
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
580            0    151.0           90.0           46.0    125.0  42.1   
418            1     83.0           68.0           29.0    125.0  18.2   
764            2    122.0           70.0           27.0    125.0  36.8   
363            4    146.0           78.0           29.0    125.0  38.5   
757            0    123.0           72.0           29.0    125.0  36.3   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
192            7    159.0           66.0           29.0    125.0  30.4   
629            4     94.0           65.0           22.0    125.0  24.7   
559           11     85.0           74.0           29.0    125.0  30.1   
684            5    136.0           82.0           29.0    125.0  32.3   

     DiabetesPedigreeFunction  Age  
580                     0.371   21  
418                     0.624   27  
764                     0.340   27  
363                     0.520   67  
757                     0.258   52  
..                        ...  ...  
763                     0.171   63  
192                     0.383   36  
629                     0.148   21  
559                     0.300   35  
684                     0.640   69  

[537 rows x 8 columns]

# Create Model

In [64]:
model_dtc = DecisionTreeClassifier()

# Fitting DecisionTreeClassifier   on dataset

In [66]:
model_dtc.fit(x_train,y_train)

DecisionTreeClassifier()

# Display Decision Tree

In [85]:
tree.plot_tree(model_dtc)

[Text(0.5171401515151515, 0.9705882352941176, 'x[1] <= 144.5\ngini = 0.462\nsamples = 537\nvalue = [194, 343]'),
 Text(0.24943181818181817, 0.9117647058823529, 'x[7] <= 28.5\ngini = 0.368\nsamples = 412\nvalue = [100, 312]'),
 Text(0.11742424242424243, 0.8529411764705882, 'x[5] <= 30.45\ngini = 0.203\nsamples = 218\nvalue = [25, 193]'),
 Text(0.048484848484848485, 0.7941176470588235, 'x[0] <= 7.0\ngini = 0.039\nsamples = 100\nvalue = [2, 98]'),
 Text(0.03636363636363636, 0.7352941176470589, 'x[4] <= 48.5\ngini = 0.02\nsamples = 99\nvalue = [1, 98]'),
 Text(0.024242424242424242, 0.6764705882352942, 'x[6] <= 0.63\ngini = 0.153\nsamples = 12\nvalue = [1, 11]'),
 Text(0.012121212121212121, 0.6176470588235294, 'gini = 0.0\nsamples = 11\nvalue = [0, 11]'),
 Text(0.03636363636363636, 0.6176470588235294, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.048484848484848485, 0.6764705882352942, 'gini = 0.0\nsamples = 87\nvalue = [0, 87]'),
 Text(0.06060606060606061, 0.7352941176470589, 'gini =

# Predict the x_test 

In [69]:
y_predict = model_dtc.predict(x_test)
y_predict

array([0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0])

# Display Training Accuracy

In [70]:
model_dtc.score(x_train,y_train)

1.0

# Display Test Accuracy

In [71]:
model_dtc.score(x_test,y_test)

0.7748917748917749

# Confusion Matrix

In [72]:
from sklearn.metrics import confusion_matrix

In [80]:
confusion_matrix(y_test,y_predict)

array([[ 49,  25],
       [ 27, 130]], dtype=int64)

# Save Model State

In [77]:
import pickle

In [78]:
f = open("model_dtc.pkl","wb")

In [79]:
pickle.dump(model_dtc,f)

# Load Model from Disk

In [82]:
f1 = open('model_dtc.pkl','rb')

In [83]:
new_model = pickle.load(f1)

In [84]:
new_model.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0])